name: StackOverflowMetric
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 1 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Stackoverflow Metric
        uses: lowlighter/metrics@latest
        with:
          output_action: none
          filename: metrics.plugin.stackoverflow.svg
          token: NOT_NEEDED
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 12359863
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 1
          plugin_stackoverflow_lines: 1
          plugin_stackoverflow_lines_snippet: 1
      - name: Metrics Mover
        if: ${{ success() || failure() }}
        run: |
          set +e
          mkdir ./metrics
          ls -la
          sudo mv /metrics_renders/* ./metrics/
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          git add --all
          git commit -m "chore: push metrics"
          git push